import LegalLayout from './LegalLayout'

export default function TermsPage({ inApp = false }) {
  return (
    <LegalLayout title="Terms of Service" updated="14 July 2026" inApp={inApp}>
      <p>Please read these Terms of Service ("Terms") carefully before using Glumbi. By creating an account or using any part of the service, you agree to be bound by these Terms.</p>

      <h2>1. About Glumbi</h2>
      <p>Glumbi is an AI-powered children's storytelling and activity platform. It is intended for use by parents and caregivers to enrich the learning and imaginative development of young children aged 1–10.</p>

      <h2>2. Eligibility</h2>
      <ul>
        <li>You must be at least 18 years old to create an account.</li>
        <li>By registering, you confirm that you are the parent or legal guardian of any child whose name and profile you add to the app.</li>
        <li>Glumbi is not intended to be used directly by children without parental supervision.</li>
      </ul>

      <h2>3. Your account</h2>
      <ul>
        <li>You are responsible for keeping your login credentials secure.</li>
        <li>You must provide accurate information when creating your account.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>Notify us immediately at <a href="mailto:support@glumbi.com">support@glumbi.com</a> if you suspect unauthorised access.</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Attempt to generate content that is violent, sexually explicit, hateful, or otherwise harmful.</li>
        <li>Use the service to train AI models or scrape content at scale.</li>
        <li>Share your account with others or resell access to the service.</li>
        <li>Attempt to bypass, disable, or circumvent any safety filter, rate limit, or security measure.</li>
        <li>Use the service for any commercial purpose without our written permission.</li>
        <li>Submit story prompts in languages other than English (prompts must be in English; stories can be listened to in 12 languages).</li>
      </ul>

      <h2>5. AI-generated content</h2>
      <ul>
        <li>Stories, activities, and curiosity answers are generated by Glumbi AI (powered by Anthropic). While we apply multiple layers of content safety filtering, AI can occasionally produce unexpected output.</li>
        <li>We do not guarantee the accuracy, completeness, or suitability of any AI-generated content.</li>
        <li>Parents should review content before sharing it with very young children.</li>
        <li>Content generated through Glumbi is for personal, non-commercial use only.</li>
      </ul>

      <h2>6. Usage limits</h2>
      <ul>
        <li>Accounts are subject to a fair-use monthly AI credit limit that resets on the 1st of each month. The current default limit is displayed on your account dashboard.</li>
        <li>Demo usage (without an account) is limited to 2 stories per IP address per day and subject to a global daily cap.</li>
        <li>We reserve the right to adjust these limits at any time with reasonable notice.</li>
      </ul>

      <h2>7. Intellectual property</h2>
      <ul>
        <li>The Glumbi name, logo, and interface design are our intellectual property.</li>
        <li>AI-generated stories and content produced through your use of the service belong to you for personal use.</li>
        <li>You grant us a limited licence to store and process your content solely to provide the service.</li>
      </ul>

      <h2>8. Termination</h2>
      <ul>
        <li>You may delete your account at any time by contacting <a href="mailto:support@glumbi.com">support@glumbi.com</a>.</li>
        <li>We may suspend or terminate accounts that violate these Terms, with or without notice.</li>
      </ul>

      <h2>9. Parental controls and device responsibility</h2>
      <ul>
        <li>Glumbi provides an in-app parental lock (PIN and session time limit) as a convenience feature to help parents manage screen time. This lock operates within the browser and cannot prevent access to browser-level settings or controls.</li>
        <li>Clearing browser cookies or cache will remove the active login session. Children who do so will be unable to log back in without the parent's credentials.</li>
        <li>Glumbi is not responsible for a child bypassing the in-app lock by accessing device or browser settings. Parents are solely responsible for configuring appropriate device-level parental controls (such as iOS Screen Time, Android Family Link, or browser-managed profiles) to supplement Glumbi's in-app features.</li>
        <li>We strongly recommend enabling device-level restrictions on any device used by a child.</li>
      </ul>

      <h2>10. Disclaimer of warranties</h2>
      <p>Glumbi is provided "as is" without warranties of any kind. We do not guarantee uninterrupted availability of the service. AI-generated content is not a substitute for professional educational, medical, or psychological advice.</p>

      <h2>11. Limitation of liability</h2>
      <p>To the fullest extent permitted by applicable law, Glumbi shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

      <h2>12. Governing law</h2>
      <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Bengaluru, India.</p>

      <h2>13. Changes to these Terms</h2>
      <p>We may update these Terms from time to time. The "last updated" date at the top of this page always reflects the current version. Continued use of the service after changes are posted constitutes acceptance of the new Terms. We recommend checking this page periodically.</p>

      <h2>14. Contact</h2>
      <p>For any questions about these Terms, email us at <a href="mailto:legal@glumbi.com">legal@glumbi.com</a>.</p>
    </LegalLayout>
  )
}
